/**
* @author        : Vasil Panovski
* @date          : November 19, 2019
* @description   : Utility class contains constants
*/
public with sharing class Constants {

    public static final String INVALID_JSON_MESSAGE = 'JSON input is Empty or Invalid';
    public static final String BATCH_PROCESSED_MESSAGE = 'Records processed by Batch Job';
    public static final String DATA_IMPORTED_MESSAGE_FORMAT = 'Processed {0} records; Failed {1} records.';
}